data:
  block_size: 512
  cnhubertsoft_gate: 10
  duration: 2
  encoder: vec768l12
  encoder_hop_size: 320
  encoder_out_channels: 768
  encoder_sample_rate: 16000
  extensions:
  - wav
  sampling_rate: 44100
  training_files: filelists/train.txt
  unit_interpolate_mode: nearest
  validation_files: filelists/val.txt
device: cuda
env:
  expdir: logs/44k/diffusion
  gpu_id: 0
infer:
  method: dpm-solver++
  speedup: 10
model:
  k_step_max: 0
  n_chans: 512
  n_hidden: 256
  n_layers: 20
  n_spk: 879
  timesteps: 1000
  type: Diffusion
  use_pitch_aug: true
spk:
  AVALLACH: 449
  Abbas_g3: 803
  Abe_g3: 291
  Abrax: 748
  Abuyin_g2: 412
  Achim Barrenstein: 264
  Agenak_g3: 64
  Agon_g2: 508
  Akil_g2: 590
  Ali_g3: 837
  Alligator Jack_g2: 342
  Alrik_g2: 43
  Altus_g3: 558
  Alvarez: 875
  "Andreas Gr\xF6ber": 667
  Angar_g2: 96
  Angel_Borderlands2_DE: 744
  Angus: 191
  Anog_g3: 570
  Arakos_g3: 329
  Armon_g3: 533
  Asam_g3: 318
  Asaru_g3: 768
  Aschnu_g3: 365
  Ash: 578
  Ass_Elite_Hard_g3: 629
  Ass_Elite_Insidious_g3: 733
  Ass_Elite_Proud_g3: 32
  Ass_Fat_Bearish_g3: 45
  Ass_Fat_Hectic_g3: 507
  Ass_Fat_Insidious_g3: 551
  Ass_Old_Hard_g3: 693
  Ass_Old_Insidious_g3: 198
  Ass_Warrior_Clear_g3: 771
  Ass_Warrior_Dumb_g3: 328
  Ass_Warrior_Hard_g3: 434
  Ass_Warrior_Proud_g3: 847
  Axton_Borderlands2_DE: 348
  BARON: 154
  BECCA: 246
  Babo_g2: 286
  Badriya: 293
  Baloro_g1: 726
  Baltram_g2: 672
  Bandaro_g3: 275
  Bandit 1_g2: 534
  Barbar (M): 714
  Barbar (W): 301
  Bartok_g2: 232
  Basir_g3: 250
  Belschwur: 565
  Ben_g3: 221
  Bengar_g2: 811
  Benito_g3: 376
  Bennet_g2: 786
  Beute-Leprechaun_Borderlands2_DE: 107
  Biff_g2: 471
  Bill_g2: 542
  Blake: 680
  Bloodwyn_g1: 790
  Bogir_g3: 576
  Bones: 126
  Bones_g2: 609
  Booze: 337
  Bosper_g2: 468
  Bradley_g3: 750
  Brago's Wache_g2: 674
  Brandon_g2: 172
  Braum: 111
  Brian_g2: 59
  Brick_Borderlands2_DE: 873
  Brogar: 234
  Bromor_g2: 299
  Brutus_g2: 494
  Bufford_g3: 694
  Bullco_g2: 825
  Buster_g2: 500
  CIRILLA: 257
  Canthar_g2: 199
  Captain Cabrera_Borderlands2_DE: 175
  Captain Scarlett_Borderlands2_DE: 77
  Carlos: 138
  Carlos_g3: 543
  Carter: 197
  Cassia_g2: 368
  Cassius_Borderlands2_DE: 108
  Cavalorn_g2: 756
  Chani: 453
  Charles_g3: 129
  Cipher_g2: 435
  Claptrap_Borderlands2_DE: 90
  Cobryn_g3: 251
  Connor_g3: 782
  Constantino_g2: 308
  Copper_g3: 690
  Cor Angar_g1: 863
  Cor Kalom_g1: 143
  Coragon_g2: 97
  Cord_g2: 647
  Cornelius_g2: 735
  Corristo_g1: 718
  Crach: 448
  Crazy Earl_Borderlands2_DE: 30
  Cronos_g1: 548
  Cruz_g3: 475
  Curtis: 258
  Curtis_g3: 833
  DANDELION: 765
  DIJKSTRA: 222
  Daiki: 650
  Danny: 788
  Danny_Borderlands2_DE: 482
  Dar_g2: 163
  Darius: 799
  Daron_g2: 849
  Daryl_g3: 485
  Datu: 495
  Davlin_Borderlands2_DE: 159
  De Wett: 445
  Delgado: 489
  Denpok_g3: 526
  Dexter: 793
  Dexter_g2: 358
  DiFuego: 446
  Diablo4_DruidM_EN: 281
  Diego_g1: 125
  Diego_g2: 132
  Diego_g3: 390
  Dolok_g3: 486
  Donovan: 3
  Dr. Patricia Tannis_Borderlands2_DE: 488
  Dr. Zed_Borderlands2_DE: 53
  Drax_g1: 785
  Dudley_g3: 395
  Dyrian_g2: 584
  "D\xE4monenj\xE4ger (M)": 49
  "D\xE4monenj\xE4ger (W)": 626
  ESKEL: 373
  Edgor_g2: 555
  Elber_g3: 639
  Elena_g2: 416
  Ellen_Borderlands2_DE: 156
  Ellie_Borderlands2_DE: 594
  Elvrich_g2: 124
  Emet_g3: 280
  Emilio_g2: 150
  Emma: 92
  Enzo: 808
  Eremit_g2: 774
  Erol_g2: 835
  Esteban_g2: 616
  Eusebio: 878
  Fabio_g3: 600
  Fajeth_g2: 305
  Farim_g2: 173
  Farmon_g3: 484
  Fasim_g3: 652
  Felipe_g3: 204
  Fence: 560
  Fernando_g2: 120
  Ferros_g2: 209
  Fester_g2: 11
  Feuernovize 1_g2: 402
  Fink_Borderlands2_DE: 867
  Finley_g3: 21
  Finn_g2: 414
  Fisk_g2: 408
  Fletcher_g1: 834
  Flint_g3: 622
  Fortuno_g2: 814
  Francis_g2: 515
  Franco_g2: 844
  Frithjof_g3: 547
  GERALT: 178
  GUSLAR: 695
  Gaan_g2: 161
  Gaige_Borderlands2_DE: 848
  Gamal_g3: 608
  Gangplank: 144
  Garcia: 211
  Gardist 2_g1: 775
  Garett_g2: 736
  Garik_g3: 268
  Garond_g2: 18
  Garvell_g2: 137
  Garwig_g2: 816
  Gelford_g3: 432
  GeraltTW1: 109
  Gerbrandt_g2: 567
  Gerold_g2: 798
  Girion_g2: 174
  Gnar_g3: 530
  Godar_g2: 598
  Gonzales_g3: 33
  Gorax_g2: 662
  Gorn_g1: 195
  Gorn_g2: 67
  Gorn_g3: 501
  Grace: 419
  Greg_g2: 796
  Grim_g1: 361
  Gritta_g2: 877
  Grok_g3: 16
  "Gro\xDFmeister": 294
  Gustava Yngelmo_Borderlands2_DE: 423
  HJALMAR: 455
  Hakeke: 550
  Hakon_g2: 113
  Halvor_g2: 4
  Hamid_g3: 134
  Handsome Jack_Borderlands2_DE: 399
  Hanna_g2: 335
  Hansi: 10
  Hanson_g3: 704
  Harad_g2: 761
  Hatlod_g3: 641
  Hawkins: 783
  Hector_Borderlands2_DE: 239
  Hector_g3: 336
  Helge Heynold: 139
  Heller_Borderlands2_DE: 403
  Helmut Winkelmann: 465
  Henry_g2: 315
  Herbert_Borderlands2_DE: 467
  Hernandez: 654
  Hernando_g3: 224
  Herold_g2: 42
  Hexendoktor (M): 557
  Hexendoktor (W): 288
  Hikoko: 311
  Hilda_g2: 562
  Hjalte_g3: 396
  Hodges_g2: 431
  Hokurn_g2: 227
  Hum_Elite_Hard_g3: 527
  Hum_Elite_Proud_g3: 705
  Hum_Fat_Bearish_g3: 691
  Hum_Fat_Weak_g3: 141
  Hum_Female_Nice_g3: 784
  Hum_Female_Strong_g3: 797
  Hum_Old_Calm_g3: 24
  Hum_Old_Weak_g3: 463
  Hum_Old_Weird_g3: 201
  Hum_Old_Wise_g3: 746
  Hum_Slave_Clever_g3: 17
  Hum_Slave_Defiant_g3: 171
  Hum_Slave_Tired_g3: 356
  Hum_Slave_Weak_g3: 202
  Hum_Warrior_Bearish_g3: 298
  Hum_Warrior_Calm_g3: 83
  Hum_Warrior_Clear_g3: 52
  Hum_Warrior_Dumb_g3: 776
  Hum_Warrior_Friendly_g3: 564
  Hum_Warrior_Hard_g3: 804
  Hum_Warrior_Proud_g3: 179
  Hum_Young_Clever_g3: 292
  Hum_Young_Naive_g3: 772
  Huno_g2: 369
  Hyglas_g2: 580
  Hyperion_Borderlands2_DE: 362
  Igaraz_g2: 245
  Ignaz_g2: 545
  Ilja_g3: 374
  Ingmar_g2: 2
  Ingvar_g3: 480
  Inog_g3: 742
  Inquisitor: 347
  Iomar_g3: 525
  Iorweth: 193
  Isabella: 363
  Ismael_g3: 499
  Jack: 61
  Jack-Lady 1_Borderlands2_DE: 93
  Jack-Lady 2_Borderlands2_DE: 493
  Jack-Lady 3_Borderlands2_DE: 80
  Jack_g2: 683
  Jackal_g1: 708
  Jaffar: 207
  Jan_g2: 745
  Jang_Borderlands2_DE: 223
  Jared_g3: 375
  Jarvis_g2: 398
  Javier_g3: 343
  Jax: 48
  Jensgar_g3: 60
  Jerek_g3: 568
  Jergan_g2: 278
  Jesper_g2: 511
  Jhin: 541
  Jinx: 841
  "Joachim P\xFCtz": 353
  Joey_g3: 739
  Jora_g2: 382
  Jorgen_g2: 341
  Jorn_g3: 78
  Joru_g1: 418
  Jose_g3: 827
  Julio_g3: 285
  KCD_Adam: 473
  KCD_Adela: 116
  KCD_Agnes: 556
  KCD_Alex: 669
  KCD_Alte Dirne: 297
  KCD_Alter Thomas: 612
  KCD_Andreas: 870
  KCD_Antonia: 723
  KCD_Apotheker: 58
  KCD_Badehausbesitzerin: 436
  KCD_Bauer Josef: 405
  KCD_Baumeister Karel: 524
  KCD_Baumler: 325
  KCD_Bedrischka: 610
  KCD_Beran: 392
  "KCD_Besch\xFCtzer Manfred": 559
  KCD_Betti: 687
  KCD_Bettlerin Jana: 677
  KCD_Bettlerin am Wegesrand: 421
  KCD_Bianca: 371
  KCD_Bischek: 386
  KCD_Boris: 206
  KCD_Bruder Bibliothekar: 668
  KCD_Bruder Kellerer: 307
  KCD_Bruder Nevlas: 483
  KCD_Bruder Nicodemus: 860
  "KCD_Bruder Pf\xF6rtner": 487
  "KCD_B\xE4cker Silvester": 456
  KCD_Circator Johann: 766
  KCD_Circator Stibor: 203
  KCD_Daniel: 634
  KCD_Der alte Blaha: 642
  "KCD_Diebischer K\xF6hler": 180
  KCD_Dorfbewohnerin 2: 303
  KCD_Drahomira: 770
  KCD_Dubek: 857
  KCD_Duellant 1: 821
  KCD_Duellant 2: 513
  KCD_Duellant 3: 862
  KCD_Elias: 140
  KCD_Elischka: 606
  "KCD_Entf\xFChrer 2": 826
  KCD_Erik: 46
  KCD_Felsen: 194
  KCD_Florian: 295
  KCD_Frau Bauer: 149
  KCD_Fritz: 755
  KCD_Gargama: 339
  KCD_Gehilfe des Inquisitors: 54
  KCD_Gerber: 728
  KCD_Guta: 274
  KCD_Hanekin Hase: 131
  KCD_Haudrauf: 575
  KCD_Hauptmann Bernard: 740
  KCD_Heinrich: 182
  KCD_Helfer des Klostermeiers: 103
  KCD_Henker Hermann: 552
  KCD_Henslin: 685
  KCD_Herold: 82
  KCD_Herr Anselm: 404
  KCD_Herr Diwisch: 537
  KCD_Herr Erhart: 830
  KCD_Herr Hagen Zul: 618
  KCD_Herr Hans Capon: 644
  KCD_Herr Hanusch von Leipa: 538
  KCD_Herr Istvan Toth: 532
  KCD_Herr Jeschek: 539
  KCD_Herr Kuno: 625
  KCD_Herr Radzig Kobyla: 514
  KCD_Herr Robard: 749
  KCD_Herr Wolflin von Kamberg: 818
  KCD_Herrin Stefanie: 713
  KCD_Hofbesitzer Bauer: 153
  KCD_Holba: 653
  "KCD_H\xE4ndler Ernst": 410
  KCD_Inquisitor Jaroslav: 581
  KCD_Jackel: 31
  KCD_Jakub: 839
  "KCD_Jan B\xE4rmann": 394
  KCD_Jaroslav: 312
  KCD_Johanka: 177
  KCD_Julian: 760
  KCD_Kampfmeister Vanyek: 357
  KCD_Karl: 452
  KCD_Karolina: 470
  KCD_Katra, Frau des Waffenschmieds: 619
  KCD_Klostermeier: 794
  KCD_Konrad Hagen: 430
  KCD_Konrad Kyeser: 340
  KCD_Kornelius: 597
  KCD_Krista: 170
  "KCD_Kr\xE4uterweib": 406
  KCD_Kunesch: 777
  "KCD_K\xE4mmerer": 238
  "KCD_K\xF6hler 1": 447
  "KCD_K\xF6hler 2": 676
  "KCD_K\xF6hler 3": 283
  "KCD_K\xF6hler-Zwilling 1": 633
  "KCD_K\xF6hler-Zwilling 2": 231
  KCD_Lagerdirne: 147
  KCD_Landstreicher: 657
  KCD_Ledetschkoer Metzger: 51
  KCD_Leschek: 379
  KCD_Margit: 72
  KCD_Marius: 216
  KCD_Markgraf Jobst: 123
  KCD_Marosch: 702
  KCD_Matthias: 843
  "KCD_Matth\xE4us": 579
  KCD_Meister Jerome: 838
  KCD_Meister Otto: 378
  KCD_Melichar: 764
  KCD_Minenarbeiterin: 235
  KCD_Mirka: 417
  KCD_Morcock: 244
  KCD_Mutter: 352
  "KCD_M\xF6rderin": 225
  "KCD_M\xFCller Oliver": 321
  "KCD_M\xFCller Peschek": 758
  "KCD_M\xFCller Simon": 727
  "KCD_M\xFCller Woyzeck": 759
  "KCD_M\xFCller bei Sasau": 146
  "KCD_M\xFCllerstochter Julia": 63
  KCD_Nachtigall: 214
  KCD_Novize Antonius: 689
  KCD_Novize Joachim: 262
  KCD_Novize Konstantin: 795
  KCD_Novize Lukas: 263
  KCD_Pater Fabian: 497
  KCD_Pater Godwin: 160
  KCD_Pater Simon: 474
  KCD_Pavel von Kolin: 762
  KCD_Pechuna: 265
  "KCD_Petr B\xE4rmann": 673
  KCD_Peychar: 88
  KCD_Pickel: 496
  "KCD_Pl\xFCnderer": 441
  KCD_Presser: 438
  KCD_Prior: 754
  KCD_Prokop: 778
  KCD_Rapota: 868
  KCD_Rattayer Metzger: 152
  KCD_Rattayer Schreiber: 210
  KCD_Rattayer Vogt: 240
  KCD_Rotschopf: 104
  KCD_Rupert: 472
  "KCD_R\xE4tselsteller": 387
  "KCD_R\xFCstschmied": 503
  KCD_Samuel: 577
  KCD_Sasauer Vogt: 518
  KCD_Scharlatan: 219
  KCD_Schmied Mikesch: 490
  KCD_Schneider Ambros: 611
  "KCD_Schr\xE4ger Vogel": 836
  KCD_Schwarzer Lukesch: 332
  KCD_Sebastian vom Berg: 345
  KCD_Skalitzer Pfarrer: 110
  KCD_Skalitzer Waffenknecht: 710
  KCD_Stallmeister: 306
  KCD_Stepan Fieder: 122
  KCD_Stibor: 502
  KCD_Stinker: 101
  KCD_Stroh: 602
  "KCD_St\xF6renfried": 802
  "KCD_Tagel\xF6hner": 731
  KCD_Talmberger Stallmeister: 706
  KCD_Theresa: 665
  KCD_Theresas Vater: 613
  KCD_Thomas aus dem Badehaus: 426
  KCD_Timmy: 732
  KCD_Tobias Feyfar: 583
  KCD_Tonda: 75
  KCD_Tratschweib: 81
  "KCD_T\xF6pfer Stanislav": 36
  KCD_Ulrich: 304
  KCD_Urban: 810
  KCD_Uschitzer Schreiber: 859
  KCD_Vater: 751
  KCD_Vatzek: 192
  KCD_Vera: 79
  KCD_Vikar: 842
  KCD_Vinzenz: 520
  KCD_Vitus: 569
  KCD_Vormann Wendel: 346
  KCD_Waffenschmied Fink: 217
  KCD_Wicht: 230
  "KCD_Wildh\xFCter Berthold": 383
  "KCD_Wildh\xFCter Nickolas": 272
  KCD_Willibald: 270
  "KCD_Wortf\xFChrer der K\xF6hler 1": 712
  "KCD_W\xE4chter Radim": 716
  KCD_Zach: 656
  KCD_Zlata: 871
  KCD_Zmola: 840
  KCD_Zora: 391
  KEIRA METZ: 850
  Kaan: 659
  Kaelin_g3: 828
  Kalan_g3: 289
  Kalesch_g3: 317
  Kalil: 460
  Kan_g3: 831
  Kapotth_g3: 492
  Kapua: 574
  Kardif_g2: 165
  Karlen_g3: 380
  Karras_g2: 20
  Karrypto_g3: 648
  Kellen der Heide_Borderlands2_DE: 331
  Keroloth_g2: 367
  Kerth_g3: 34
  Khabir_g3: 212
  Kjorn_g2: 420
  Knut_g3: 260
  Konrad_g3: 323
  Kreuzritter (M): 604
  Kreuzritter (W): 85
  Krieg_Borderlands2_DE: 829
  Kurgan_g2: 820
  LAMBERT: 517
  Lares_g2: 522
  Lares_g3: 861
  Largo: 237
  Lars_g3: 874
  Lee_g1: 466
  Lee_g2: 635
  Lehmar_g2: 824
  Leif_g3: 68
  Lester_g1: 617
  Lester_g2: 40
  Lester_g3: 722
  Leto: 701
  Leuvaarden: 462
  Lilith_Borderlands2_DE: 664
  Lobart_g2: 682
  Logan_g2: 296
  Loggins_Borderlands2_DE: 721
  Lorath: 413
  Lord Andre_g2: 743
  Lord Hagen_g2: 566
  Lorenzo: 319
  Lothar_g2: 663
  Lt Col Space Helicopters_Borderlands2_DE: 37
  Luca_g3: 851
  Luis: 184
  Lukar_g3: 561
  Malak_g2: 5
  Maleth_g2: 277
  Mamuk_g3: 55
  Mannig_g3: 397
  Marcus_Borderlands2_DE: 185
  Marduk_g2: 135
  Maria_g2: 333
  Marik_g3: 697
  Mario_g2: 0
  Marius_g3: 189
  Markus_g3: 510
  Marshall Friedman_Borderlands2_DE: 228
  Martha die Heidin_Borderlands2_DE: 344
  Martin_g2: 554
  Masil_g3: 439
  Maskenmann_Borderlands2_DE: 181
  Mason_g3: 593
  Matt_g2: 681
  Matteo_g2: 142
  Mauregato: 372
  Maya_Borderlands2_DE: 703
  Meeks: 741
  Merdarion_g2: 491
  Merdarion_g3: 273
  Mezir_g3: 585
  Michael Betz: 313
  Michael Lucke: 255
  Mick Zaford_Borderlands2_DE: 661
  Miles: 476
  Milok_g3: 753
  Milten_g1: 187
  Milten_g2: 719
  Milten_g3: 15
  Mirzo_g3: 186
  Mitch_g3: 338
  Moe_g2: 686
  Mojok_g3: 607
  Montera-Orc_g3: 688
  Montera_BarKeeper_01_g3: 800
  Moralischer Typ_Borderlands2_DE: 806
  Mordecai_Borderlands2_DE: 632
  Morgan_g2: 773
  Morris: 360
  Moxxi_Borderlands2_DE: 427
  Mud_g1: 592
  Murat_g3: 364
  Myxir_g2: 679
  Myxir_g3: 516
  "M\xF6nch (M)": 666
  "M\xF6nch (W)": 620
  "M\xF6rderlin_Borderlands2_DE": 118
  NOVIGRAD RICH MAN 01: 119
  Nadja_g2: 354
  Nafalem_g3: 815
  Nagur_g2: 645
  Naher Typ_Borderlands2_DE: 384
  Nakutu: 587
  Namenloser Held_g1: 302
  Namenloser Held_g2: 158
  Narrator: 259
  Nasib_g3: 164
  Navaras_g3: 752
  Nefarius_g2: 865
  Nefarius_g3: 385
  Nemrok_g3: 407
  Neoras_g2: 730
  Nerusul_g3: 563
  Nick Benjamin: 50
  Ningal_g3: 519
  Norris_g3: 845
  OBrian: 253
  Ogre: 167
  Olf: 38
  Oma Flexington_Borderlands2_DE: 696
  Onar_g2: 544
  Opolos_g2: 698
  Orc_Boss_Clear_g3: 377
  Orc_Boss_Hard_g3: 627
  Orc_Old_Calm_g3: 469
  Orc_Old_Insidious_g3: 660
  Orc_Warrior_Bearish_g3: 359
  Orc_Warrior_Dumb_g3: 95
  Orc_Warrior_Hard_g3: 74
  Orc_Warrior_Proud_g3: 433
  Oric_g2: 805
  Orlan_g2: 188
  Orry_g1: 509
  Osmund_g3: 13
  Osorio: 588
  Pablo_g2: 866
  Paladin 1_g2: 300
  Pandu: 623
  Parcival_g2: 98
  Parlan_g2: 443
  Patty: 256
  Pedro: 717
  Pedro_g2: 176
  Phil_g3: 71
  Piratenkoch_g2: 242
  Player: 599
  Player_g3: 349
  Potros_g3: 457
  Pranck_g3: 553
  "Pr\xE4sident Smith_Borderlands2_DE": 22
  Pyran_g3: 327
  Pyrokar_g2: 388
  Rachel: 200
  Rakus_g3: 852
  Ramirez_g2: 39
  Ramon_g2: 512
  Ramon_g3: 26
  Ranapiri: 872
  Randolph_g2: 789
  Raoul_g2: 249
  Rasul_g3: 320
  Rathgar_g3: 572
  Raufbold: 127
  Regis_g2: 601
  Rengaru_g2: 621
  Reto_g3: 252
  Rhobar_g3: 523
  Richter_g2: 271
  Rick: 763
  Riordian_g2: 229
  Riordian_g3: 316
  Rod_g2: 14
  Roland_Borderlands2_DE: 876
  Roland_g3: 276
  Romanov: 442
  Roquefort: 692
  Rosi_g2: 350
  Rovold_g3: 792
  Rufus_g3: 428
  Rumford: 282
  Runak_g3: 145
  Rune_g3: 479
  Rupert_g2: 779
  Russel_g3: 105
  Sagitta_g2: 675
  Salvador_Borderlands2_DE: 47
  Sam: 700
  Samuel_g2: 757
  Sancho_g2: 813
  Sancho_g3: 638
  Sanford_g3: 444
  Santiago: 254
  Sara: 546
  Saskia: 628
  Saturas_g1: 236
  Saturas_g2: 215
  Saturas_g3: 699
  Scatty_g1: 94
  Scatty_g2: 595
  Schiffswache 2_g2: 62
  Scooter_Borderlands2_DE: 738
  Sebastian_g3: 366
  Sebastiano: 66
  Sekob_g2: 869
  Sentenza_g2: 190
  "Seraph-Kristall-Verk\xE4ufer_Borderlands2_DE": 573
  Serpentes_g2: 450
  Shade_Borderlands2_DE: 529
  Shakyor_g3: 56
  Shawn_g3: 671
  SiburNarad_g3: 314
  Sigmor_g3: 415
  Silvio_g3: 678
  Sir Hammerlock_Borderlands2_DE: 640
  Sivert_g3: 130
  Skip_g2: 549
  Slayne: 809
  Small Timmy_Borderlands2_DE: 205
  Snaf: 241
  Snaf_g2: 84
  Sobota_g3: 106
  Sophia: 715
  Stahlbart: 166
  Sugut_g3: 787
  Syble Jentz_Borderlands2_DE: 571
  Sylvio_g2: 322
  "S\xF6ldner 1_g2": 121
  "S\xFCdtorwache 1_g2": 858
  TRISS: 819
  Tahana: 454
  Talbin_g2: 148
  Tarok_g3: 451
  Tector Hodunk_Borderlands2_DE: 521
  Tempeck_g3: 102
  ThalerTW1: 614
  Thekla_g2: 355
  Thorus_g1: 725
  Thorus_g3: 112
  Throben_g2: 162
  Till_g2: 767
  Tiny Tina_Borderlands2_DE: 459
  Tippler_g3: 596
  Tizgar_g3: 155
  Tjalf_g3: 65
  Tom_g3: 409
  Torgue_Borderlands2_DE: 630
  Torlof_g2: 464
  Torn_g3: 27
  "Totenbeschw\xF6rer (M)": 853
  "Totenbeschw\xF6rer (W)": 128
  Tran Concelmo_Borderlands2_DE: 19
  Treslott_g3: 603
  Tufail_g3: 99
  Udar_g2: 196
  Ugolf_g3: 498
  Ugrasal_g3: 832
  Ulf_g2: 70
  Ulthar_g2: 247
  Ulvi: 684
  Umbrak_g3: 284
  Ur-Shak: 86
  Uruk_g3: 528
  VERDEN PEASANT 03: 855
  VESEMIR: 605
  Vak_g3: 734
  Varek_g3: 115
  Vasco_g3: 720
  Vatras_g2: 220
  Vatras_g3: 646
  Vaughn_Borderlands2_DE: 330
  Veanna_Borderlands2_DE: 400
  Venturo: 504
  Viran_g1: 649
  Wasili_g2: 218
  Wegelagerer_g2: 309
  Wenzel_g3: 643
  Wilson_g3: 370
  Wolf_g1: 136
  Wolf_g2: 658
  Wulfgar_g2: 381
  Xardas_g1: 817
  Xardas_g2: 823
  Xardas_g3: 637
  YENNEFER: 44
  Yanier Winters_Borderlands2_DE: 440
  Yasuo: 25
  Yussuf_g3: 73
  ZOLTAN CHIVAY: 461
  Zac: 624
  Zapotek_g3: 151
  Zauberer (M): 724
  Zauberer (W): 393
  Zer0_Borderlands2_DE: 326
  Zombie TK Baha_Borderlands2_DE: 481
  Zuben_g3: 422
  Zuris_g2: 100
  demoman: 651
  dlc1femaleuniquevalerica: 411
  dlc1maleuniquedexion: 864
  dlc1maleuniquegaran: 334
  dlc1maleuniquegelebor: 69
  dlc1maleuniquegunmar: 540
  dlc1maleuniqueharkon: 233
  dlc1maleuniqueisran: 582
  dlc1seranavoice: 670
  dlc2femaledarkelfcommoner: 822
  dlc2femaleuniquefrea: 248
  dlc2maledarkelfcommoner: 28
  dlc2maledarkelfcynical: 437
  dlc2maleuniqueadril: 208
  dlc2maleuniquemodyn: 267
  dlc2maleuniqueneloth: 458
  dlc2maleuniquestorn: 747
  dlc2rieklingvoice: 812
  engineer: 351
  femaleargonian: 12
  femalechild: 183
  femalecommander: 114
  femalecommoner: 57
  femalecondescending: 261
  femalecoward: 9
  femaledarkelf: 425
  femaleelfhaughty: 707
  femaleeventoned: 290
  femalekhajiit: 424
  femalenord: 1
  femaleoldgrumpy: 8
  femaleoldkindly: 536
  femaleorc: 157
  femaleshrill: 801
  femalesultry: 168
  femaleuniqueastrid: 846
  femaleuniquedelphine: 243
  femaleuniquekarliah: 856
  femaleuniquemaven: 711
  femaleuniquemirabelleervine: 87
  femaleuniquevex: 505
  femaleyoungeager: 91
  heavy: 729
  maleargonian: 780
  malebandit: 6
  malebrute: 709
  malechild: 781
  malecommander: 506
  malecommoner: 117
  malecommoneraccented: 854
  malecondescending: 807
  malecoward: 266
  maledarkelf: 7
  maledrunk: 586
  maleelfhaughty: 615
  maleeventoned: 655
  maleeventonedaccented: 591
  maleforsworn: 478
  maleguard: 310
  malekhajiit: 589
  malenord: 213
  malenordcommander: 769
  maleoldgrumpy: 324
  maleoldkindly: 401
  maleorc: 169
  maleslycynical: 41
  malesoldier: 389
  maleuniquearngeir: 429
  maleuniquebrynjolf: 76
  maleuniquecicero: 477
  maleuniquedelvinmallory: 226
  maleuniqueesbern: 89
  maleuniquegalmar: 35
  maleuniquehadvar: 791
  maleuniquekodlakwhitemane: 636
  maleuniquemercerfrey: 631
  maleuniquenazir: 269
  maleuniquetullius: 23
  maleuniqueulfric: 737
  maleyoungeager: 287
  medic: 29
  sniper: 279
  sniper_deep: 531
  soldier: 133
  spy: 535
train:
  amp_dtype: fp32
  batch_size: 48
  cache_all_data: true
  cache_device: cpu
  cache_fp16: true
  decay_step: 100000
  epochs: 100000
  gamma: 0.5
  interval_force_save: 5000
  interval_log: 10
  interval_val: 2000
  lr: 0.0001
  num_workers: 4
  save_opt: false
  weight_decay: 0
vocoder:
  ckpt: pretrain/nsf_hifigan/model
  type: nsf-hifigan
